### ISSUE TITLE
define custom commands ?

### ISSUE THREAD

**Issue by bt-maps** [hnimminh/luaredis#1]
Great Lua client. Is it possible to define custom commands in the client? I use a different database based on the RESP protocol. Most Redis clients in other languages work no problem.

examples would look like this:
JSET user 901 name Tom
JGET user 901

Thanks

**Comment by hnimminh** [comment]
Hi @bt-maps, 
Not sure what is your usecase, can explain more?

**Comment by bt-maps** [comment]
How do I run a User-definable command? this is listed in the main features section https://github.com/hnimminh/luaredis#main-features

Thanks

**Comment by hnimminh** [comment]
is this what you looking for 
- https://github.com/hnimminh/luaredis/blob/master/examples/define_commands.lua 
- https://redis.io/commands/eval/
